#!/usr/bin/env python3
"""Bundle a cync-lan-lib checkout into custom_components/cync_lan/_vendor.

Deploy branch only. Home Assistant reinstalls URL requirements on every
start with `uv pip install --upgrade`, which needs the internet, so the
deploy branch ships the library inside the integration instead and lists
the library's own dependencies as plain requirements.

Never edit _vendor by hand; re-run this script:

    python scripts/bundle_lib.py --lib ~/projects/personal/cync-lan-lib \
        --ref feature/effects-parity --release 2.15.0-tp.1
"""

from __future__ import annotations

import argparse
import io
import json
import shutil
import subprocess
import tarfile
import tomllib
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any

VENDOR_REL = Path("custom_components/cync_lan/_vendor")
MANIFEST_REL = Path("custom_components/cync_lan/manifest.json")
LIB_SRC = "src/cync_lan"

README = """# Bundled cync_lan library (generated)

Generated by `scripts/bundle_lib.py` from cync-lan-lib commit {commit}
(ref `{ref}`), bundled version `{version}`. Do not edit anything in this
directory by hand: change cync-lan-lib, commit, and re-run the script.

The integration's `__init__.py` puts this directory first on `sys.path`, so
`import cync_lan` loads this copy instead of any PyPI install, and the
`dist-info` here makes `importlib.metadata.version("cync-lan")` report it.
"""


class BundleError(Exception):
    """Refused to bundle (dirty checkout, unknown ref, URL requirement)."""


@dataclass(frozen=True)
class BundleInfo:
    lib_commit: str
    lib_version: str
    bundled_version: str
    release: str
    requirements: list[str]


def _git(lib: Path, *args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(lib), *args], check=True, capture_output=True, text=True
    ).stdout.strip()


def _req_name(req: str) -> str:
    """'PyYAML>=6.0.2' -> 'pyyaml' (PEP 503 normalised, no extras/markers)."""
    name = req
    for i, ch in enumerate(req):
        if ch in "<>=!~;[ @":
            name = req[:i]
            break
    return name.strip().lower().replace("_", "-").replace(".", "-")


def merge_requirements(integration_reqs: list[str], lib_reqs: list[str]) -> list[str]:
    """The integration's own requirements minus cync-lan, plus the library's
    runtime dependencies. Where both name a package, the library's specifier
    wins. Sorted by package name. URL requirements are refused."""
    merged: dict[str, str] = {}
    for req in integration_reqs:
        if _req_name(req) != "cync-lan":
            merged[_req_name(req)] = req
    for req in lib_reqs:
        merged[_req_name(req)] = req
    for req in merged.values():
        if "://" in req or " @ " in req or req.startswith("git+"):
            raise BundleError(f"URL requirement not allowed: {req}")
    return [merged[name] for name in sorted(merged)]


def _remote(lib: Path) -> str:
    try:
        return _git(lib, "remote", "get-url", "origin")
    except subprocess.CalledProcessError:
        return ""


def bundle(lib: Path, ref: str, root: Path, release: str) -> BundleInfo:
    if _git(lib, "status", "--porcelain"):
        raise BundleError(f"{lib} has uncommitted changes; commit or stash first")
    try:
        commit = _git(lib, "rev-parse", "--verify", "--quiet", f"{ref}^{{commit}}")
    except subprocess.CalledProcessError as err:
        raise BundleError(f"unknown ref {ref!r} in {lib}") from err

    pyproject: dict[str, Any] = tomllib.loads(
        _git(lib, "show", f"{commit}:pyproject.toml")
    )
    lib_version = str(pyproject["project"]["version"])
    lib_reqs = [str(r) for r in pyproject["project"].get("dependencies", [])]
    bundled_version = f"{lib_version}+tp.{commit[:7]}"

    manifest_path = root / MANIFEST_REL
    manifest = json.loads(manifest_path.read_text())
    requirements = merge_requirements(list(manifest.get("requirements", [])), lib_reqs)

    archive = subprocess.run(
        ["git", "-C", str(lib), "archive", "--format=tar", commit, LIB_SRC],
        check=True,
        capture_output=True,
    ).stdout

    vendor = root / VENDOR_REL
    if vendor.exists():
        shutil.rmtree(vendor)
    vendor.mkdir(parents=True)

    with tarfile.open(fileobj=io.BytesIO(archive)) as tar:
        for member in tar.getmembers():
            parts = PurePosixPath(member.name).parts
            if not member.isfile() or len(parts) < 3 or "__pycache__" in parts:
                continue
            dest = vendor.joinpath(*parts[1:])  # drop the leading "src/"
            dest.parent.mkdir(parents=True, exist_ok=True)
            extracted = tar.extractfile(member)
            assert extracted is not None
            dest.write_bytes(extracted.read())

    dist = vendor / f"cync_lan-{bundled_version}.dist-info"
    dist.mkdir()
    (dist / "METADATA").write_text(
        f"Metadata-Version: 2.1\nName: cync-lan\nVersion: {bundled_version}\n"
    )
    (dist / "top_level.txt").write_text("cync_lan\n")

    (vendor / "VENDORED.json").write_text(
        json.dumps(
            {
                "lib_remote": _remote(lib),
                "ref": ref,
                "commit": commit,
                "lib_version": lib_version,
                "bundled_version": bundled_version,
                "release": release,
                "lib_requirements": lib_reqs,
            },
            indent=2,
        )
        + "\n"
    )
    (vendor / "README.md").write_text(
        README.format(commit=commit, ref=ref, version=bundled_version)
    )

    manifest["requirements"] = requirements
    manifest["version"] = release
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")

    return BundleInfo(commit, lib_version, bundled_version, release, requirements)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--lib", type=Path, required=True, help="cync-lan-lib checkout")
    parser.add_argument("--ref", required=True, help="branch, tag or commit to bundle")
    parser.add_argument("--release", required=True, help="e.g. 2.15.0-tp.1")
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="integration repo root (default: this repo)",
    )
    args = parser.parse_args()
    try:
        info = bundle(args.lib.expanduser(), args.ref, args.root, args.release)
    except BundleError as err:
        raise SystemExit(f"bundle_lib: {err}") from err
    print(f"bundled cync_lan {info.bundled_version} (lib {info.lib_commit})")
    print(f"manifest version {info.release}, requirements {info.requirements}")


if __name__ == "__main__":
    main()
